kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker_1"
    extraMounts:
      - hostPath: ./data
        containerPath: /tmp/data
      - hostPath: /Users/trungtran/Documents/Personal/Project/deploy_airflow_on_k8s_local/dags
        containerPath: /tmp/dags
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker_2"
    extraMounts:
      - hostPath: ./data
        containerPath: /tmp/data
      - hostPath: /Users/trungtran/Documents/Personal/Project/deploy_airflow_on_k8s_local/dags
        containerPath: /tmp/dags
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker_3"
    extraMounts:
      - hostPath: ./data
        containerPath: /tmp/data
      - hostPath: /Users/trungtran/Documents/Personal/Project/deploy_airflow_on_k8s_local/dags
        containerPath: /tmp/dags
